image: node:12.5.0
stages:
  - build
  - deploy

build:
  stage: build
  script: 
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script: 
    - apt-get install lftp -y
    - lftp -e "open ftp://vh95.hoster.by; user $FTP_USER $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose dist/ job.sova.by/; bye"
