image: node:12.5.0
stages:
  - build
  - deploy

build:
  stage: build
  script: 
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script: 
    - ls dist
    - echo "running deploy"
